name: esptouch_example
description: Demonstrates how to use the esptouch plugin.
publish_to: 'none'
version: 0.1.5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: any
  firebase_database: ^3.1.3
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  provider: ^2.0.0+1




dev_dependencies:
  flutter_test:
    sdk: flutter

  esptouch_flutter:
    path: ../

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans SC
      fonts:
        - asset: assets/fonts/NotoSansSC-Bold.ttf
        - asset: assets/fonts/NotoSansSC-Light.ttf
        - asset: assets/fonts/NotoSansSC-Medium.ttf
        - asset: assets/fonts/NotoSansSC-Regular.ttf

    - family: Alfa Slab One
      fonts:
        - asset: assets/fonts/AlfaSlabOne-Regular.ttf

    - family: Chivo
      fonts:
        - asset: assets/fonts/Chivo-Bold.ttf
        - asset: assets/fonts/Chivo-Regular.ttf
  assets:
    - assets/images/
    - assets/logo/


module:
  androidX: true